sources:
  datalake.order_items:
    type: s3
    bucket_name: sources
    file_name: order_items_dataset
    file_extension: csv
destination:
  destination_type: s3
  bucket_name: raw-data
  file_name: order_items.parquet