sources:
  datalake.order_payments:
    type: s3
    bucket_name: sources
    file_name: order_payments_dataset
    file_extension: csv
destination:
  destination_type: s3
  bucket_name: raw-data
  file_name: order_payments.parquet