sources:
  datalake.order_reviews:
    type: s3
    bucket_name: sources
    file_name: order_reviews_dataset
    file_extension: csv
destination:
  destination_type: s3
  bucket_name: raw-data
  file_name: order_reviews.parquet